### ISSUE TITLE
I can't connect to site via VC Manager

### ISSUE THREAD

**Issue by kodermax** [VirtoCommerce/vc-community#26]
I install my site to azure  cloud service, and i can't connect to site via VC Manager

**Comment by Woland2k** [comment]
What is your site URL and how did you install it? (using powershell scripts, using web platform installer or manually deploying through VS.NET)

**Comment by kodermax** [comment]
http://motulshop-www.cloudapp.net/
I deploying through VS.NET

**Comment by Woland2k** [comment]
Do you have database installed and configured? It seems like there is one setup. You need to specify database connection string manually when installing through VS.NET.

**Comment by kodermax** [comment]
My database installed and configured. 
My error:



Event code: 3005 
Event message: An unhandled exception has occurred. 
Event time: 1/27/2015 7:10:43 PM 
Event time (UTC): 1/27/2015 7:10:43 PM 
Event ID: b30dabe71552491aa3a2fc1d5605dc43 
Event sequence: 4 
Event occurrence: 1 
Event detail code: 0 
 
Application information: 
    Application domain: /LM/W3SVC/1273337584/ROOT-1-130668594224750537 
    Trust level: Full 
    Application Virtual Path: / 
    Application Path: F:\sitesroot\0\ 
    Machine name: RD0003FF582C7D 
 
Process information: 
    Process ID: 3448 
    Process name: w3wp.exe 
    Account name: NT AUTHORITY\NETWORK SERVICE 
 
Exception information: 
    Exception type: NullReferenceException 
    Exception message: Object reference not set to an instance of an object.
   at VirtoCommerce.Web.Client.Extensions.Routing.Routes.StoreRoute.GetRouteData(HttpContextBase httpContext)
   at VirtoCommerce.Web.Client.Extensions.Routing.Routes.ItemRoute.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 
 
Request information: 
    Request URL: http://100.112.80.29/Error/Oops?aspxerrorpath=/ 
    Request path: /Error/Oops 
    User host address: 100.112.80.29 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: NT AUTHORITY\NETWORK SERVICE 
 
Thread information: 
    Thread ID: 7 
    Thread account name: NT AUTHORITY\NETWORK SERVICE 
    Is impersonating: False 
    Stack trace:    at VirtoCommerce.Web.Client.Extensions.Routing.Routes.StoreRoute.GetRouteData(HttpContextBase httpContext)
   at VirtoCommerce.Web.Client.Extensions.Routing.Routes.ItemRoute.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.RouteCollection.GetRouteData(HttpContextBase httpContext)
   at System.Web.Routing.UrlRoutingModule.PostResolveRequestCache(HttpContextBase context)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
 
 
Custom event details:

**Comment by kodermax** [comment]
I found error. Не срабатывали настройки azure. Сработали локальные настройки подключения к БД и elasticsearch.

**Comment by Woland2k** [comment]
Yes, you need to set those in settings in azure cloud service
